version: '3.8'

services:
  apache:
    build: ./apache
    environment:
      - DOCKER_PHP_HOST=php
    ports:
      - "8086:80"
    depends_on:
      - php
    networks:
      - appnet

  php:
    build: ./php
    networks:
      - appnet

networks:
  appnet:
